name: .NET 8 CI (Build and Test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Added version
    
    # Setup .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4  # Added version
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # Cache NuGet packages for faster builds
    - name: Cache NuGet packages
      uses: actions/cache@v4  # Added version
      with:
        path: |
          ~/.nuget/packages
          **/bin
          **/obj
        key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-dotnet-
    
    # Build the solution
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    # Run MSTest tests
    - name: Test with MSTest
      run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
    
    # Upload test results (optional)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4  # Added version
      with:
        name: test-results
        path: '**/TestResults/*.trx'