name: .NET 8 CD (Azure Deployment)

on:
  workflow_run:
    workflows: [".NET 8 CI (Build and Test)"]
    branches: [main]
    types:
      - completed

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: 'your-app-name'  # Replace with your Azure app name
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Added version
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4  # Added version
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Publish the app
      run: |
        dotnet publish -c Release -o ${{ github.workspace }}/publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2  # Explicit version (v2 is stable)
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Fixed typo (PROFILE not PROFILE)
        package: ${{ github.workspace }}/publish